export const candidates= [{
    id:1,
    name:'Neeraj',
    symbol:'Nc',
    url:'www.nikku.com',
    email:'neeraj@gmail.com'
},{
    id:2,
    name:'Yashu',
    symbol:'Nc',
    url:'www.nikku.com',
    email:'neeraj@gmail.com'
},{
    id:3,
    name:'Karan',
    symbol:'Nc',
    url:'www.nikku.com',
    email:'neeraj@gmail.com'
},];