const products = [
    {
      name: "Giant BBQ",
      image: "https://i.imgur.com/yPreV19.png",
      description: `Grilled chicken, beef, fish, sausages, bacon, 
        vegetables served with chips.`,
      location: "Kimironko Market",
      owner: "0x32Be343B94f860124dC4fEe278FDCBD38C102D88",
      price: 3,
      sold: 27,
      index: 0,
    },
    {
      name: "BBQ Chicken",
      image: "https://i.imgur.com/NMEzoYb.png",
      description: `French fries and grilled chicken served with gacumbari 
        and avocados with cheese.`,
      location: "Afrika Fresh KG 541 St",
      owner: "0x3275B7F400cCdeBeDaf0D8A9a7C8C1aBE2d747Ea",
      price: 4,
      sold: 12,
      index: 1,
    },
    {
      name: "Beef burrito",
      image: "https://i.imgur.com/RNlv3S6.png",
      description: `Homemade tortilla with your choice of filling, cheese, 
        guacamole salsa with Mexican refried beans and rice.`,
      location: "Asili - KN 4 St",
      owner: "0x2EF48F32eB0AEB90778A2170a0558A941b72BFFb",
      price: 2,
      sold: 35,
      index: 2,
    },
    {
      name: "Barbecue Pizza",
      image: "https://i.imgur.com/fpiDeFd.png",
      description: `Barbecue Chicken Pizza: Chicken, gouda, pineapple, onions 
        and house-made BBQ sauce.`,
      location: "Kigali Hut KG 7 Ave",
      owner: "0x2EF48F32eB0AEB90778A2170a0558A941b72BFFb",
      price: 1,
      sold: 2,
      index: 3,
    },
  ]